package xyz.yakdmt.navremote.database;

import de.greenrobot.dao.DaoException;
import xyz.yakdmt.navremote.utils.Saveable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CARGO".
 */
public class Cargo implements java.io.Serializable, Saveable {

    private String id;
    private String transport;
    private String master_document;
    private String sender_code;
    private String sender_name;
    private String appearance_date;
    private String destination_checkpoint_code;
    private String transport_line_code;
    private String transport_line_name;
    private String client_name;
    private String description;
    private String insurance_amount;
    private String insurance;
    private String count;
    private String weight;
    private String volume;
    private String occurence_checkpoint_type;
    private String occurence_checkpoint_code;
    private String destination_checkpoint_type;
    private String currency_code;
    private String cost;
    private String customs_clearance;
    private String broker_code;
    private String broker_name;
    private String delivery_conditions;
    private String priority;
    private String processing_mode;
    private String consignee_code;
    private String consignee_name;
    private String route;
    private String contract_number;
    private String performer_type;
    private String performer_id;
    private String performer_name;
    private String status;
    private String expected_departure_date;
    private String expected_arrival_date;
    private String ready_state;
    private String container_number;
    private String department_name;
    private String product_count;
    private String dt_registration_date;
    private String documents_check_date;
    private String customs_payment_date;
    private String release_date;
    private String inspectial_date;
    private String terminal;
    private String extradited_from_stock;
    private String customs_start_date;
    private String customs_end_date;
    private String executed_works;
    private String client_id;
    private String order_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CargoDao myDao;

    private Client client;
    private String client__resolvedKey;

    private Order order;
    private String order__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Cargo() {
    }

    public Cargo(String id) {
        this.id = id;
    }

    public Cargo(String id, String transport, String master_document, String sender_code, String sender_name, String appearance_date, String destination_checkpoint_code, String transport_line_code, String transport_line_name, String client_name, String description, String insurance_amount, String insurance, String count, String weight, String volume, String occurence_checkpoint_type, String occurence_checkpoint_code, String destination_checkpoint_type, String currency_code, String cost, String customs_clearance, String broker_code, String broker_name, String delivery_conditions, String priority, String processing_mode, String consignee_code, String consignee_name, String route, String contract_number, String performer_type, String performer_id, String performer_name, String status, String expected_departure_date, String expected_arrival_date, String ready_state, String container_number, String department_name, String product_count, String dt_registration_date, String documents_check_date, String customs_payment_date, String release_date, String inspectial_date, String terminal, String extradited_from_stock, String customs_start_date, String customs_end_date, String executed_works, String client_id, String order_id) {
        this.id = id;
        this.transport = transport;
        this.master_document = master_document;
        this.sender_code = sender_code;
        this.sender_name = sender_name;
        this.appearance_date = appearance_date;
        this.destination_checkpoint_code = destination_checkpoint_code;
        this.transport_line_code = transport_line_code;
        this.transport_line_name = transport_line_name;
        this.client_name = client_name;
        this.description = description;
        this.insurance_amount = insurance_amount;
        this.insurance = insurance;
        this.count = count;
        this.weight = weight;
        this.volume = volume;
        this.occurence_checkpoint_type = occurence_checkpoint_type;
        this.occurence_checkpoint_code = occurence_checkpoint_code;
        this.destination_checkpoint_type = destination_checkpoint_type;
        this.currency_code = currency_code;
        this.cost = cost;
        this.customs_clearance = customs_clearance;
        this.broker_code = broker_code;
        this.broker_name = broker_name;
        this.delivery_conditions = delivery_conditions;
        this.priority = priority;
        this.processing_mode = processing_mode;
        this.consignee_code = consignee_code;
        this.consignee_name = consignee_name;
        this.route = route;
        this.contract_number = contract_number;
        this.performer_type = performer_type;
        this.performer_id = performer_id;
        this.performer_name = performer_name;
        this.status = status;
        this.expected_departure_date = expected_departure_date;
        this.expected_arrival_date = expected_arrival_date;
        this.ready_state = ready_state;
        this.container_number = container_number;
        this.department_name = department_name;
        this.product_count = product_count;
        this.dt_registration_date = dt_registration_date;
        this.documents_check_date = documents_check_date;
        this.customs_payment_date = customs_payment_date;
        this.release_date = release_date;
        this.inspectial_date = inspectial_date;
        this.terminal = terminal;
        this.extradited_from_stock = extradited_from_stock;
        this.customs_start_date = customs_start_date;
        this.customs_end_date = customs_end_date;
        this.executed_works = executed_works;
        this.client_id = client_id;
        this.order_id = order_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCargoDao() : null;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTransport() {
        return transport;
    }

    public void setTransport(String transport) {
        this.transport = transport;
    }

    public String getMaster_document() {
        return master_document;
    }

    public void setMaster_document(String master_document) {
        this.master_document = master_document;
    }

    public String getSender_code() {
        return sender_code;
    }

    public void setSender_code(String sender_code) {
        this.sender_code = sender_code;
    }

    public String getSender_name() {
        return sender_name;
    }

    public void setSender_name(String sender_name) {
        this.sender_name = sender_name;
    }

    public String getAppearance_date() {
        return appearance_date;
    }

    public void setAppearance_date(String appearance_date) {
        this.appearance_date = appearance_date;
    }

    public String getDestination_checkpoint_code() {
        return destination_checkpoint_code;
    }

    public void setDestination_checkpoint_code(String destination_checkpoint_code) {
        this.destination_checkpoint_code = destination_checkpoint_code;
    }

    public String getTransport_line_code() {
        return transport_line_code;
    }

    public void setTransport_line_code(String transport_line_code) {
        this.transport_line_code = transport_line_code;
    }

    public String getTransport_line_name() {
        return transport_line_name;
    }

    public void setTransport_line_name(String transport_line_name) {
        this.transport_line_name = transport_line_name;
    }

    public String getClient_name() {
        return client_name;
    }

    public void setClient_name(String client_name) {
        this.client_name = client_name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getInsurance_amount() {
        return insurance_amount;
    }

    public void setInsurance_amount(String insurance_amount) {
        this.insurance_amount = insurance_amount;
    }

    public String getInsurance() {
        return insurance;
    }

    public void setInsurance(String insurance) {
        this.insurance = insurance;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getVolume() {
        return volume;
    }

    public void setVolume(String volume) {
        this.volume = volume;
    }

    public String getOccurence_checkpoint_type() {
        return occurence_checkpoint_type;
    }

    public void setOccurence_checkpoint_type(String occurence_checkpoint_type) {
        this.occurence_checkpoint_type = occurence_checkpoint_type;
    }

    public String getOccurence_checkpoint_code() {
        return occurence_checkpoint_code;
    }

    public void setOccurence_checkpoint_code(String occurence_checkpoint_code) {
        this.occurence_checkpoint_code = occurence_checkpoint_code;
    }

    public String getDestination_checkpoint_type() {
        return destination_checkpoint_type;
    }

    public void setDestination_checkpoint_type(String destination_checkpoint_type) {
        this.destination_checkpoint_type = destination_checkpoint_type;
    }

    public String getCurrency_code() {
        return currency_code;
    }

    public void setCurrency_code(String currency_code) {
        this.currency_code = currency_code;
    }

    public String getCost() {
        return cost;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }

    public String getCustoms_clearance() {
        return customs_clearance;
    }

    public void setCustoms_clearance(String customs_clearance) {
        this.customs_clearance = customs_clearance;
    }

    public String getBroker_code() {
        return broker_code;
    }

    public void setBroker_code(String broker_code) {
        this.broker_code = broker_code;
    }

    public String getBroker_name() {
        return broker_name;
    }

    public void setBroker_name(String broker_name) {
        this.broker_name = broker_name;
    }

    public String getDelivery_conditions() {
        return delivery_conditions;
    }

    public void setDelivery_conditions(String delivery_conditions) {
        this.delivery_conditions = delivery_conditions;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getProcessing_mode() {
        return processing_mode;
    }

    public void setProcessing_mode(String processing_mode) {
        this.processing_mode = processing_mode;
    }

    public String getConsignee_code() {
        return consignee_code;
    }

    public void setConsignee_code(String consignee_code) {
        this.consignee_code = consignee_code;
    }

    public String getConsignee_name() {
        return consignee_name;
    }

    public void setConsignee_name(String consignee_name) {
        this.consignee_name = consignee_name;
    }

    public String getRoute() {
        return route;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    public String getContract_number() {
        return contract_number;
    }

    public void setContract_number(String contract_number) {
        this.contract_number = contract_number;
    }

    public String getPerformer_type() {
        return performer_type;
    }

    public void setPerformer_type(String performer_type) {
        this.performer_type = performer_type;
    }

    public String getPerformer_id() {
        return performer_id;
    }

    public void setPerformer_id(String performer_id) {
        this.performer_id = performer_id;
    }

    public String getPerformer_name() {
        return performer_name;
    }

    public void setPerformer_name(String performer_name) {
        this.performer_name = performer_name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getExpected_departure_date() {
        return expected_departure_date;
    }

    public void setExpected_departure_date(String expected_departure_date) {
        this.expected_departure_date = expected_departure_date;
    }

    public String getExpected_arrival_date() {
        return expected_arrival_date;
    }

    public void setExpected_arrival_date(String expected_arrival_date) {
        this.expected_arrival_date = expected_arrival_date;
    }

    public String getReady_state() {
        return ready_state;
    }

    public void setReady_state(String ready_state) {
        this.ready_state = ready_state;
    }

    public String getContainer_number() {
        return container_number;
    }

    public void setContainer_number(String container_number) {
        this.container_number = container_number;
    }

    public String getDepartment_name() {
        return department_name;
    }

    public void setDepartment_name(String department_name) {
        this.department_name = department_name;
    }

    public String getProduct_count() {
        return product_count;
    }

    public void setProduct_count(String product_count) {
        this.product_count = product_count;
    }

    public String getDt_registration_date() {
        return dt_registration_date;
    }

    public void setDt_registration_date(String dt_registration_date) {
        this.dt_registration_date = dt_registration_date;
    }

    public String getDocuments_check_date() {
        return documents_check_date;
    }

    public void setDocuments_check_date(String documents_check_date) {
        this.documents_check_date = documents_check_date;
    }

    public String getCustoms_payment_date() {
        return customs_payment_date;
    }

    public void setCustoms_payment_date(String customs_payment_date) {
        this.customs_payment_date = customs_payment_date;
    }

    public String getRelease_date() {
        return release_date;
    }

    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    public String getInspectial_date() {
        return inspectial_date;
    }

    public void setInspectial_date(String inspectial_date) {
        this.inspectial_date = inspectial_date;
    }

    public String getTerminal() {
        return terminal;
    }

    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    public String getExtradited_from_stock() {
        return extradited_from_stock;
    }

    public void setExtradited_from_stock(String extradited_from_stock) {
        this.extradited_from_stock = extradited_from_stock;
    }

    public String getCustoms_start_date() {
        return customs_start_date;
    }

    public void setCustoms_start_date(String customs_start_date) {
        this.customs_start_date = customs_start_date;
    }

    public String getCustoms_end_date() {
        return customs_end_date;
    }

    public void setCustoms_end_date(String customs_end_date) {
        this.customs_end_date = customs_end_date;
    }

    public String getExecuted_works() {
        return executed_works;
    }

    public void setExecuted_works(String executed_works) {
        this.executed_works = executed_works;
    }

    public String getClient_id() {
        return client_id;
    }

    public void setClient_id(String client_id) {
        this.client_id = client_id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    /** To-one relationship, resolved on first access. */
    public Client getClient() {
        String __key = this.client_id;
        if (client__resolvedKey == null || client__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ClientDao targetDao = daoSession.getClientDao();
            Client clientNew = targetDao.load(__key);
            synchronized (this) {
                client = clientNew;
            	client__resolvedKey = __key;
            }
        }
        return client;
    }

    public void setClient(Client client) {
        synchronized (this) {
            this.client = client;
            client_id = client == null ? null : client.getId();
            client__resolvedKey = client_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Order getOrder() {
        String __key = this.order_id;
        if (order__resolvedKey == null || order__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            OrderDao targetDao = daoSession.getOrderDao();
            Order orderNew = targetDao.load(__key);
            synchronized (this) {
                order = orderNew;
            	order__resolvedKey = __key;
            }
        }
        return order;
    }

    public void setOrder(Order order) {
        synchronized (this) {
            this.order = order;
            order_id = order == null ? null : order.getId();
            order__resolvedKey = order_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void save() {
        DaoTask.getInstance().getSession().getCargoDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
