package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CLIENT".
 */
public class Client implements java.io.Serializable {

    private String id;
    private String name;
    private String last_comment;
    private String email;
    private String phone;
    private String contact;
    private String address;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Client() {
    }

    public Client(String id) {
        this.id = id;
    }

    public Client(String id, String name, String last_comment, String email, String phone, String contact, String address) {
        this.id = id;
        this.name = name;
        this.last_comment = last_comment;
        this.email = email;
        this.phone = phone;
        this.contact = contact;
        this.address = address;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLast_comment() {
        return last_comment;
    }

    public void setLast_comment(String last_comment) {
        this.last_comment = last_comment;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
