package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONTACT".
 */
public class Contact implements java.io.Serializable {

    private String id;
    private String client_id;
    private String name;
    private String client_name;
    private String postal_index;
    private String region_code;
    private String firm_name;
    private String phone;
    private String mobile_phone;
    private String manager_code;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Contact() {
    }

    public Contact(String id) {
        this.id = id;
    }

    public Contact(String id, String client_id, String name, String client_name, String postal_index, String region_code, String firm_name, String phone, String mobile_phone, String manager_code) {
        this.id = id;
        this.client_id = client_id;
        this.name = name;
        this.client_name = client_name;
        this.postal_index = postal_index;
        this.region_code = region_code;
        this.firm_name = firm_name;
        this.phone = phone;
        this.mobile_phone = mobile_phone;
        this.manager_code = manager_code;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getClient_id() {
        return client_id;
    }

    public void setClient_id(String client_id) {
        this.client_id = client_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClient_name() {
        return client_name;
    }

    public void setClient_name(String client_name) {
        this.client_name = client_name;
    }

    public String getPostal_index() {
        return postal_index;
    }

    public void setPostal_index(String postal_index) {
        this.postal_index = postal_index;
    }

    public String getRegion_code() {
        return region_code;
    }

    public void setRegion_code(String region_code) {
        this.region_code = region_code;
    }

    public String getFirm_name() {
        return firm_name;
    }

    public void setFirm_name(String firm_name) {
        this.firm_name = firm_name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile_phone() {
        return mobile_phone;
    }

    public void setMobile_phone(String mobile_phone) {
        this.mobile_phone = mobile_phone;
    }

    public String getManager_code() {
        return manager_code;
    }

    public void setManager_code(String manager_code) {
        this.manager_code = manager_code;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
