package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import xyz.yakdmt.navremote.utils.Column;
import xyz.yakdmt.navremote.utils.Saveable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONTACT".
 */
public class Contact implements java.io.Serializable, Saveable {

     @Column(name = "Но.")
    private String id;
     @Column(name = "Название")
    private String name;
     @Column(name = "Клиент")
    private String client_id;
     @Column(name = "Название Фирмы")
    private String client_name;
     @Column(name = "Почтовый Индекс")
    private String postal_index;
     @Column(name = "Код страны/региона")
    private String region_code;
     @Column(name = "Телефон")
    private String phone;
     @Column(name = "Мобильный Телефон")
    private String mobile_phone;
     @Column(name = "Факс")
    private String fax;
     @Column(name = "Код Менеджера")
    private String manager_code;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Contact() {
    }

    public Contact(String id) {
        this.id = id;
    }

    public Contact(String id, String name, String client_id, String client_name, String postal_index, String region_code, String phone, String mobile_phone, String fax, String manager_code) {
        this.id = id;
        this.name = name;
        this.client_id = client_id;
        this.client_name = client_name;
        this.postal_index = postal_index;
        this.region_code = region_code;
        this.phone = phone;
        this.mobile_phone = mobile_phone;
        this.fax = fax;
        this.manager_code = manager_code;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClient_id() {
        return client_id;
    }

    public void setClient_id(String client_id) {
        this.client_id = client_id;
    }

    public String getClient_name() {
        return client_name;
    }

    public void setClient_name(String client_name) {
        this.client_name = client_name;
    }

    public String getPostal_index() {
        return postal_index;
    }

    public void setPostal_index(String postal_index) {
        this.postal_index = postal_index;
    }

    public String getRegion_code() {
        return region_code;
    }

    public void setRegion_code(String region_code) {
        this.region_code = region_code;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile_phone() {
        return mobile_phone;
    }

    public void setMobile_phone(String mobile_phone) {
        this.mobile_phone = mobile_phone;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getManager_code() {
        return manager_code;
    }

    public void setManager_code(String manager_code) {
        this.manager_code = manager_code;
    }

    // KEEP METHODS - put your custom methods here
    public void save() {
        DaoTask.getInstance().getSession().getContactDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
