package xyz.yakdmt.navremote.database;

import de.greenrobot.dao.DaoException;
import xyz.yakdmt.navremote.utils.Saveable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DELIVERY".
 */
public class Delivery implements java.io.Serializable, Saveable {

    private String id;
    private String transportation_method;
    private String status;
    private String auto_train_number;
    private String auto_carrier;
    private String description;
    private String client_name;
    private String cargo_description;
    private String expected_start_date;
    private String actual_start_date;
    private String start_checkpoint_name;
    private String finish_checkpoint_name;
    private String start_country;
    private String expected_arrival_terminal_date;
    private String actual_arrival_terminal_date;
    private String terminal_name;
    private String receiver_name;
    private String actual_release_terminal_date;
    private String actual_finish_date;
    private String performer_name;
    private String gtd_release_date;
    private String gtd_number;
    private String container_number;
    private String wagon_number;
    private String cargo_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DeliveryDao myDao;

    private Cargo cargo;
    private String cargo__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Delivery() {
    }

    public Delivery(String id) {
        this.id = id;
    }

    public Delivery(String id, String transportation_method, String status, String auto_train_number, String auto_carrier, String description, String client_name, String cargo_description, String expected_start_date, String actual_start_date, String start_checkpoint_name, String finish_checkpoint_name, String start_country, String expected_arrival_terminal_date, String actual_arrival_terminal_date, String terminal_name, String receiver_name, String actual_release_terminal_date, String actual_finish_date, String performer_name, String gtd_release_date, String gtd_number, String container_number, String wagon_number, String cargo_id) {
        this.id = id;
        this.transportation_method = transportation_method;
        this.status = status;
        this.auto_train_number = auto_train_number;
        this.auto_carrier = auto_carrier;
        this.description = description;
        this.client_name = client_name;
        this.cargo_description = cargo_description;
        this.expected_start_date = expected_start_date;
        this.actual_start_date = actual_start_date;
        this.start_checkpoint_name = start_checkpoint_name;
        this.finish_checkpoint_name = finish_checkpoint_name;
        this.start_country = start_country;
        this.expected_arrival_terminal_date = expected_arrival_terminal_date;
        this.actual_arrival_terminal_date = actual_arrival_terminal_date;
        this.terminal_name = terminal_name;
        this.receiver_name = receiver_name;
        this.actual_release_terminal_date = actual_release_terminal_date;
        this.actual_finish_date = actual_finish_date;
        this.performer_name = performer_name;
        this.gtd_release_date = gtd_release_date;
        this.gtd_number = gtd_number;
        this.container_number = container_number;
        this.wagon_number = wagon_number;
        this.cargo_id = cargo_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDeliveryDao() : null;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTransportation_method() {
        return transportation_method;
    }

    public void setTransportation_method(String transportation_method) {
        this.transportation_method = transportation_method;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAuto_train_number() {
        return auto_train_number;
    }

    public void setAuto_train_number(String auto_train_number) {
        this.auto_train_number = auto_train_number;
    }

    public String getAuto_carrier() {
        return auto_carrier;
    }

    public void setAuto_carrier(String auto_carrier) {
        this.auto_carrier = auto_carrier;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getClient_name() {
        return client_name;
    }

    public void setClient_name(String client_name) {
        this.client_name = client_name;
    }

    public String getCargo_description() {
        return cargo_description;
    }

    public void setCargo_description(String cargo_description) {
        this.cargo_description = cargo_description;
    }

    public String getExpected_start_date() {
        return expected_start_date;
    }

    public void setExpected_start_date(String expected_start_date) {
        this.expected_start_date = expected_start_date;
    }

    public String getActual_start_date() {
        return actual_start_date;
    }

    public void setActual_start_date(String actual_start_date) {
        this.actual_start_date = actual_start_date;
    }

    public String getStart_checkpoint_name() {
        return start_checkpoint_name;
    }

    public void setStart_checkpoint_name(String start_checkpoint_name) {
        this.start_checkpoint_name = start_checkpoint_name;
    }

    public String getFinish_checkpoint_name() {
        return finish_checkpoint_name;
    }

    public void setFinish_checkpoint_name(String finish_checkpoint_name) {
        this.finish_checkpoint_name = finish_checkpoint_name;
    }

    public String getStart_country() {
        return start_country;
    }

    public void setStart_country(String start_country) {
        this.start_country = start_country;
    }

    public String getExpected_arrival_terminal_date() {
        return expected_arrival_terminal_date;
    }

    public void setExpected_arrival_terminal_date(String expected_arrival_terminal_date) {
        this.expected_arrival_terminal_date = expected_arrival_terminal_date;
    }

    public String getActual_arrival_terminal_date() {
        return actual_arrival_terminal_date;
    }

    public void setActual_arrival_terminal_date(String actual_arrival_terminal_date) {
        this.actual_arrival_terminal_date = actual_arrival_terminal_date;
    }

    public String getTerminal_name() {
        return terminal_name;
    }

    public void setTerminal_name(String terminal_name) {
        this.terminal_name = terminal_name;
    }

    public String getReceiver_name() {
        return receiver_name;
    }

    public void setReceiver_name(String receiver_name) {
        this.receiver_name = receiver_name;
    }

    public String getActual_release_terminal_date() {
        return actual_release_terminal_date;
    }

    public void setActual_release_terminal_date(String actual_release_terminal_date) {
        this.actual_release_terminal_date = actual_release_terminal_date;
    }

    public String getActual_finish_date() {
        return actual_finish_date;
    }

    public void setActual_finish_date(String actual_finish_date) {
        this.actual_finish_date = actual_finish_date;
    }

    public String getPerformer_name() {
        return performer_name;
    }

    public void setPerformer_name(String performer_name) {
        this.performer_name = performer_name;
    }

    public String getGtd_release_date() {
        return gtd_release_date;
    }

    public void setGtd_release_date(String gtd_release_date) {
        this.gtd_release_date = gtd_release_date;
    }

    public String getGtd_number() {
        return gtd_number;
    }

    public void setGtd_number(String gtd_number) {
        this.gtd_number = gtd_number;
    }

    public String getContainer_number() {
        return container_number;
    }

    public void setContainer_number(String container_number) {
        this.container_number = container_number;
    }

    public String getWagon_number() {
        return wagon_number;
    }

    public void setWagon_number(String wagon_number) {
        this.wagon_number = wagon_number;
    }

    public String getCargo_id() {
        return cargo_id;
    }

    public void setCargo_id(String cargo_id) {
        this.cargo_id = cargo_id;
    }

    /** To-one relationship, resolved on first access. */
    public Cargo getCargo() {
        String __key = this.cargo_id;
        if (cargo__resolvedKey == null || cargo__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CargoDao targetDao = daoSession.getCargoDao();
            Cargo cargoNew = targetDao.load(__key);
            synchronized (this) {
                cargo = cargoNew;
            	cargo__resolvedKey = __key;
            }
        }
        return cargo;
    }

    public void setCargo(Cargo cargo) {
        synchronized (this) {
            this.cargo = cargo;
            cargo_id = cargo == null ? null : cargo.getId();
            cargo__resolvedKey = cargo_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void save() {
        DaoTask.getInstance().getSession().getDeliveryDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
