package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import de.greenrobot.dao.DaoException;
import xyz.yakdmt.navremote.utils.Column;
import xyz.yakdmt.navremote.utils.Saveable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "DOCUMENT".
 */
public class Document implements Saveable {

    /** Not-null value. */
    private String id;
     @Column(name = "Объект Но.")
    private String order_id;
     @Column(name = "Line No.")
    private String string_number;
     @Column(name = "Тип")
    private String type;
     @Column(name = "Документ Но.")
    private String document_name;
     @Column(name = "Комментарий")
    private String comment;
     @Column(name = "Имя Файла")
    private String document_path;
     @Column(name = "Создал")
    private String creator;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Document() {
    }

    public Document(String id) {
        this.id = id;
    }

    public Document(String id, String order_id, String string_number, String type, String document_name, String comment, String document_path, String creator) {
        this.id = id;
        this.order_id = order_id;
        this.string_number = string_number;
        this.type = type;
        this.document_name = document_name;
        this.comment = comment;
        this.document_path = document_path;
        this.creator = creator;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getString_number() {
        return string_number;
    }

    public void setString_number(String string_number) {
        this.string_number = string_number;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDocument_name() {
        return document_name;
    }

    public void setDocument_name(String document_name) {
        this.document_name = document_name;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getDocument_path() {
        return document_path;
    }

    public void setDocument_path(String document_path) {
        this.document_path = document_path;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void save() {
        DaoTask.getInstance().getSession().getDocumentDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
