package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import de.greenrobot.dao.DaoException;
import xyz.yakdmt.navremote.utils.Column;
import xyz.yakdmt.navremote.utils.Saveable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "DOCUMENT".
 */
public class Document implements Saveable {

     @Column(name = "йййййййй")
    private String orderId;
    private Long id;
     @Column(name = "йййййййй")
    private String document_name;
     @Column(name = "йййййййй")
    private String document_path;
     @Column(name = "йййййййй")
    private String creator;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Document() {
    }

    public Document(Long id) {
        this.id = id;
    }

    public Document(String orderId, Long id, String document_name, String document_path, String creator) {
        this.orderId = orderId;
        this.id = id;
        this.document_name = document_name;
        this.document_path = document_path;
        this.creator = creator;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocument_name() {
        return document_name;
    }

    public void setDocument_name(String document_name) {
        this.document_name = document_name;
    }

    public String getDocument_path() {
        return document_path;
    }

    public void setDocument_path(String document_path) {
        this.document_path = document_path;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void save() {
        DaoTask.getInstance().getSession().getDocumentDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
