package xyz.yakdmt.navremote.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import xyz.yakdmt.navremote.database.Order;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER".
*/
public class OrderDao extends AbstractDao<Order, String> {

    public static final String TABLENAME = "ORDER";

    /**
     * Properties of entity Order.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Manager = new Property(3, String.class, "manager", false, "MANAGER");
        public final static Property Document_path = new Property(4, String.class, "document_path", false, "DOCUMENT_PATH");
        public final static Property Performer_code = new Property(5, String.class, "performer_code", false, "PERFORMER_CODE");
        public final static Property Performer_name = new Property(6, String.class, "performer_name", false, "PERFORMER_NAME");
        public final static Property State = new Property(7, String.class, "state", false, "STATE");
        public final static Property Dangerous = new Property(8, String.class, "dangerous", false, "DANGEROUS");
        public final static Property Receiver_code = new Property(9, String.class, "receiver_code", false, "RECEIVER_CODE");
        public final static Property Receiver_name = new Property(10, String.class, "receiver_name", false, "RECEIVER_NAME");
        public final static Property Declarant_code = new Property(11, String.class, "declarant_code", false, "DECLARANT_CODE");
        public final static Property Declarant_name = new Property(12, String.class, "declarant_name", false, "DECLARANT_NAME");
        public final static Property Declarant_department = new Property(13, String.class, "declarant_department", false, "DECLARANT_DEPARTMENT");
        public final static Property Transport = new Property(14, String.class, "transport", false, "TRANSPORT");
        public final static Property Departure_date = new Property(15, String.class, "departure_date", false, "DEPARTURE_DATE");
        public final static Property Departure_country_code = new Property(16, String.class, "departure_country_code", false, "DEPARTURE_COUNTRY_CODE");
        public final static Property Departure_country_name = new Property(17, String.class, "departure_country_name", false, "DEPARTURE_COUNTRY_NAME");
        public final static Property Departure_checkpoint_type = new Property(18, String.class, "departure_checkpoint_type", false, "DEPARTURE_CHECKPOINT_TYPE");
        public final static Property Departure_checkpoint_code = new Property(19, String.class, "departure_checkpoint_code", false, "DEPARTURE_CHECKPOINT_CODE");
        public final static Property Departure_checkpoint_name = new Property(20, String.class, "departure_checkpoint_name", false, "DEPARTURE_CHECKPOINT_NAME");
        public final static Property Departure_checkpoint_address = new Property(21, String.class, "departure_checkpoint_address", false, "DEPARTURE_CHECKPOINT_ADDRESS");
        public final static Property Destination_country_code = new Property(22, String.class, "destination_country_code", false, "DESTINATION_COUNTRY_CODE");
        public final static Property Destination_country_name = new Property(23, String.class, "destination_country_name", false, "DESTINATION_COUNTRY_NAME");
        public final static Property Destination_checkpoint_type = new Property(24, String.class, "destination_checkpoint_type", false, "DESTINATION_CHECKPOINT_TYPE");
        public final static Property Destination_checkpoint_code = new Property(25, String.class, "destination_checkpoint_code", false, "DESTINATION_CHECKPOINT_CODE");
        public final static Property Destination_checkpoint_name = new Property(26, String.class, "destination_checkpoint_name", false, "DESTINATION_CHECKPOINT_NAME");
        public final static Property Destination_checkpoint_address = new Property(27, String.class, "destination_checkpoint_address", false, "DESTINATION_CHECKPOINT_ADDRESS");
        public final static Property Brutto_weight = new Property(28, String.class, "brutto_weight", false, "BRUTTO_WEIGHT");
        public final static Property Netto_weight = new Property(29, String.class, "netto_weight", false, "NETTO_WEIGHT");
        public final static Property Volume = new Property(30, String.class, "volume", false, "VOLUME");
        public final static Property Count = new Property(31, String.class, "count", false, "COUNT");
        public final static Property Cargo_description = new Property(32, String.class, "cargo_description", false, "CARGO_DESCRIPTION");
        public final static Property Client_name = new Property(33, String.class, "client_name", false, "CLIENT_NAME");
        public final static Property Comment = new Property(34, String.class, "comment", false, "COMMENT");
        public final static Property Contact_id = new Property(35, String.class, "contact_id", false, "CONTACT_ID");
        public final static Property Cargo_id = new Property(36, String.class, "cargo_id", false, "CARGO_ID");
        public final static Property DeliveryId = new Property(37, String.class, "deliveryId", false, "DELIVERY_ID");
    };

    private DaoSession daoSession;


    public OrderDao(DaoConfig config) {
        super(config);
    }
    
    public OrderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: id
                "\"DATE\" TEXT," + // 1: date
                "\"TIME\" TEXT," + // 2: time
                "\"MANAGER\" TEXT," + // 3: manager
                "\"DOCUMENT_PATH\" TEXT," + // 4: document_path
                "\"PERFORMER_CODE\" TEXT," + // 5: performer_code
                "\"PERFORMER_NAME\" TEXT," + // 6: performer_name
                "\"STATE\" TEXT," + // 7: state
                "\"DANGEROUS\" TEXT," + // 8: dangerous
                "\"RECEIVER_CODE\" TEXT," + // 9: receiver_code
                "\"RECEIVER_NAME\" TEXT," + // 10: receiver_name
                "\"DECLARANT_CODE\" TEXT," + // 11: declarant_code
                "\"DECLARANT_NAME\" TEXT," + // 12: declarant_name
                "\"DECLARANT_DEPARTMENT\" TEXT," + // 13: declarant_department
                "\"TRANSPORT\" TEXT," + // 14: transport
                "\"DEPARTURE_DATE\" TEXT," + // 15: departure_date
                "\"DEPARTURE_COUNTRY_CODE\" TEXT," + // 16: departure_country_code
                "\"DEPARTURE_COUNTRY_NAME\" TEXT," + // 17: departure_country_name
                "\"DEPARTURE_CHECKPOINT_TYPE\" TEXT," + // 18: departure_checkpoint_type
                "\"DEPARTURE_CHECKPOINT_CODE\" TEXT," + // 19: departure_checkpoint_code
                "\"DEPARTURE_CHECKPOINT_NAME\" TEXT," + // 20: departure_checkpoint_name
                "\"DEPARTURE_CHECKPOINT_ADDRESS\" TEXT," + // 21: departure_checkpoint_address
                "\"DESTINATION_COUNTRY_CODE\" TEXT," + // 22: destination_country_code
                "\"DESTINATION_COUNTRY_NAME\" TEXT," + // 23: destination_country_name
                "\"DESTINATION_CHECKPOINT_TYPE\" TEXT," + // 24: destination_checkpoint_type
                "\"DESTINATION_CHECKPOINT_CODE\" TEXT," + // 25: destination_checkpoint_code
                "\"DESTINATION_CHECKPOINT_NAME\" TEXT," + // 26: destination_checkpoint_name
                "\"DESTINATION_CHECKPOINT_ADDRESS\" TEXT," + // 27: destination_checkpoint_address
                "\"BRUTTO_WEIGHT\" TEXT," + // 28: brutto_weight
                "\"NETTO_WEIGHT\" TEXT," + // 29: netto_weight
                "\"VOLUME\" TEXT," + // 30: volume
                "\"COUNT\" TEXT," + // 31: count
                "\"CARGO_DESCRIPTION\" TEXT," + // 32: cargo_description
                "\"CLIENT_NAME\" TEXT," + // 33: client_name
                "\"COMMENT\" TEXT," + // 34: comment
                "\"CONTACT_ID\" TEXT," + // 35: contact_id
                "\"CARGO_ID\" TEXT," + // 36: cargo_id
                "\"DELIVERY_ID\" TEXT);"); // 37: deliveryId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Order entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String manager = entity.getManager();
        if (manager != null) {
            stmt.bindString(4, manager);
        }
 
        String document_path = entity.getDocument_path();
        if (document_path != null) {
            stmt.bindString(5, document_path);
        }
 
        String performer_code = entity.getPerformer_code();
        if (performer_code != null) {
            stmt.bindString(6, performer_code);
        }
 
        String performer_name = entity.getPerformer_name();
        if (performer_name != null) {
            stmt.bindString(7, performer_name);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(8, state);
        }
 
        String dangerous = entity.getDangerous();
        if (dangerous != null) {
            stmt.bindString(9, dangerous);
        }
 
        String receiver_code = entity.getReceiver_code();
        if (receiver_code != null) {
            stmt.bindString(10, receiver_code);
        }
 
        String receiver_name = entity.getReceiver_name();
        if (receiver_name != null) {
            stmt.bindString(11, receiver_name);
        }
 
        String declarant_code = entity.getDeclarant_code();
        if (declarant_code != null) {
            stmt.bindString(12, declarant_code);
        }
 
        String declarant_name = entity.getDeclarant_name();
        if (declarant_name != null) {
            stmt.bindString(13, declarant_name);
        }
 
        String declarant_department = entity.getDeclarant_department();
        if (declarant_department != null) {
            stmt.bindString(14, declarant_department);
        }
 
        String transport = entity.getTransport();
        if (transport != null) {
            stmt.bindString(15, transport);
        }
 
        String departure_date = entity.getDeparture_date();
        if (departure_date != null) {
            stmt.bindString(16, departure_date);
        }
 
        String departure_country_code = entity.getDeparture_country_code();
        if (departure_country_code != null) {
            stmt.bindString(17, departure_country_code);
        }
 
        String departure_country_name = entity.getDeparture_country_name();
        if (departure_country_name != null) {
            stmt.bindString(18, departure_country_name);
        }
 
        String departure_checkpoint_type = entity.getDeparture_checkpoint_type();
        if (departure_checkpoint_type != null) {
            stmt.bindString(19, departure_checkpoint_type);
        }
 
        String departure_checkpoint_code = entity.getDeparture_checkpoint_code();
        if (departure_checkpoint_code != null) {
            stmt.bindString(20, departure_checkpoint_code);
        }
 
        String departure_checkpoint_name = entity.getDeparture_checkpoint_name();
        if (departure_checkpoint_name != null) {
            stmt.bindString(21, departure_checkpoint_name);
        }
 
        String departure_checkpoint_address = entity.getDeparture_checkpoint_address();
        if (departure_checkpoint_address != null) {
            stmt.bindString(22, departure_checkpoint_address);
        }
 
        String destination_country_code = entity.getDestination_country_code();
        if (destination_country_code != null) {
            stmt.bindString(23, destination_country_code);
        }
 
        String destination_country_name = entity.getDestination_country_name();
        if (destination_country_name != null) {
            stmt.bindString(24, destination_country_name);
        }
 
        String destination_checkpoint_type = entity.getDestination_checkpoint_type();
        if (destination_checkpoint_type != null) {
            stmt.bindString(25, destination_checkpoint_type);
        }
 
        String destination_checkpoint_code = entity.getDestination_checkpoint_code();
        if (destination_checkpoint_code != null) {
            stmt.bindString(26, destination_checkpoint_code);
        }
 
        String destination_checkpoint_name = entity.getDestination_checkpoint_name();
        if (destination_checkpoint_name != null) {
            stmt.bindString(27, destination_checkpoint_name);
        }
 
        String destination_checkpoint_address = entity.getDestination_checkpoint_address();
        if (destination_checkpoint_address != null) {
            stmt.bindString(28, destination_checkpoint_address);
        }
 
        String brutto_weight = entity.getBrutto_weight();
        if (brutto_weight != null) {
            stmt.bindString(29, brutto_weight);
        }
 
        String netto_weight = entity.getNetto_weight();
        if (netto_weight != null) {
            stmt.bindString(30, netto_weight);
        }
 
        String volume = entity.getVolume();
        if (volume != null) {
            stmt.bindString(31, volume);
        }
 
        String count = entity.getCount();
        if (count != null) {
            stmt.bindString(32, count);
        }
 
        String cargo_description = entity.getCargo_description();
        if (cargo_description != null) {
            stmt.bindString(33, cargo_description);
        }
 
        String client_name = entity.getClient_name();
        if (client_name != null) {
            stmt.bindString(34, client_name);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(35, comment);
        }
 
        String contact_id = entity.getContact_id();
        if (contact_id != null) {
            stmt.bindString(36, contact_id);
        }
 
        String cargo_id = entity.getCargo_id();
        if (cargo_id != null) {
            stmt.bindString(37, cargo_id);
        }
 
        String deliveryId = entity.getDeliveryId();
        if (deliveryId != null) {
            stmt.bindString(38, deliveryId);
        }
    }

    @Override
    protected void attachEntity(Order entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Order readEntity(Cursor cursor, int offset) {
        Order entity = new Order( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // manager
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // document_path
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // performer_code
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // performer_name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // state
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // dangerous
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // receiver_code
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // receiver_name
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // declarant_code
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // declarant_name
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // declarant_department
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // transport
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // departure_date
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // departure_country_code
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // departure_country_name
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // departure_checkpoint_type
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // departure_checkpoint_code
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // departure_checkpoint_name
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // departure_checkpoint_address
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // destination_country_code
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // destination_country_name
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // destination_checkpoint_type
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // destination_checkpoint_code
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // destination_checkpoint_name
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // destination_checkpoint_address
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // brutto_weight
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // netto_weight
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // volume
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // count
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // cargo_description
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // client_name
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // comment
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // contact_id
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // cargo_id
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37) // deliveryId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Order entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setManager(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDocument_path(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPerformer_code(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPerformer_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setState(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDangerous(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setReceiver_code(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setReceiver_name(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDeclarant_code(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDeclarant_name(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDeclarant_department(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTransport(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setDeparture_date(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDeparture_country_code(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setDeparture_country_name(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setDeparture_checkpoint_type(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDeparture_checkpoint_code(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDeparture_checkpoint_name(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDeparture_checkpoint_address(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setDestination_country_code(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setDestination_country_name(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setDestination_checkpoint_type(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setDestination_checkpoint_code(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setDestination_checkpoint_name(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setDestination_checkpoint_address(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setBrutto_weight(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setNetto_weight(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setVolume(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setCount(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setCargo_description(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setClient_name(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setComment(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setContact_id(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setCargo_id(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setDeliveryId(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Order entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Order entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCargoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getDeliveryDao().getAllColumns());
            builder.append(" FROM ORDER T");
            builder.append(" LEFT JOIN CONTACT T0 ON T.\"CONTACT_ID\"=T0.\"ID\"");
            builder.append(" LEFT JOIN CARGO T1 ON T.\"CARGO_ID\"=T1.\"ID\"");
            builder.append(" LEFT JOIN DELIVERY T2 ON T.\"DELIVERY_ID\"=T2.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Order loadCurrentDeep(Cursor cursor, boolean lock) {
        Order entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Contact contact = loadCurrentOther(daoSession.getContactDao(), cursor, offset);
        entity.setContact(contact);
        offset += daoSession.getContactDao().getAllColumns().length;

        Cargo cargo = loadCurrentOther(daoSession.getCargoDao(), cursor, offset);
        entity.setCargo(cargo);
        offset += daoSession.getCargoDao().getAllColumns().length;

        Delivery delivery = loadCurrentOther(daoSession.getDeliveryDao(), cursor, offset);
        entity.setDelivery(delivery);

        return entity;    
    }

    public Order loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Order> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Order> list = new ArrayList<Order>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Order> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Order> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
