package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import xyz.yakdmt.navremote.utils.Column;
import xyz.yakdmt.navremote.utils.Saveable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCT".
 */
public class Product implements Saveable {

    /** Not-null value. */
    private String id;
     @Column(name = "Заявка Но.")
    private String order_id;
     @Column(name = "Строка Но.")
    private String string_number;
     @Column(name = "Вес Брутто(кг)")
    private String brutto_weight;
     @Column(name = "Количество")
    private String count;
     @Column(name = "Описание/Комментарий")
    private String description;
     @Column(name = "Ед. Измерения")
    private String measure_unit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Product() {
    }

    public Product(String id) {
        this.id = id;
    }

    public Product(String id, String order_id, String string_number, String brutto_weight, String count, String description, String measure_unit) {
        this.id = id;
        this.order_id = order_id;
        this.string_number = string_number;
        this.brutto_weight = brutto_weight;
        this.count = count;
        this.description = description;
        this.measure_unit = measure_unit;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getString_number() {
        return string_number;
    }

    public void setString_number(String string_number) {
        this.string_number = string_number;
    }

    public String getBrutto_weight() {
        return brutto_weight;
    }

    public void setBrutto_weight(String brutto_weight) {
        this.brutto_weight = brutto_weight;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMeasure_unit() {
        return measure_unit;
    }

    public void setMeasure_unit(String measure_unit) {
        this.measure_unit = measure_unit;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void save() {
        DaoTask.getInstance().getSession().getProductDao().insertOrReplace(this);
    }
    // KEEP METHODS END

}
