package xyz.yakdmt.navremote.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCT".
 */
public class Product {

    /** Not-null value. */
    private String id;
    private String order_id;
    private String string_number;
    private String brutto_weight;
    private String count;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Product() {
    }

    public Product(String id) {
        this.id = id;
    }

    public Product(String id, String order_id, String string_number, String brutto_weight, String count, String description) {
        this.id = id;
        this.order_id = order_id;
        this.string_number = string_number;
        this.brutto_weight = brutto_weight;
        this.count = count;
        this.description = description;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getString_number() {
        return string_number;
    }

    public void setString_number(String string_number) {
        this.string_number = string_number;
    }

    public String getBrutto_weight() {
        return brutto_weight;
    }

    public void setBrutto_weight(String brutto_weight) {
        this.brutto_weight = brutto_weight;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
